<div class="jumbotron">
    <div class="container">
        <h1><?php echo $this->translate('Hello, world!');?></h1>
        <p><?php echo $this->translate('I\'m a basic Leveret application.');?></p>
    </div>
</div>


<div class="container">

    <p><?php echo $this->translate('Check some samples here:');?></p>
    <ul>
        <li><a href="/samples/view-helpers">Use of some view helpers</a></li>
        <li><a href="/samples/partials">Use of partials</a></li>
        <li><a href="/samples/vars/Leveret">A route with vars</a></li>
    </ul>

</div>
