<?php
/** @var array $fruits */
/** @var array $tableHeaders */
/** @var array $tableData */
?>

<div class="container">

    <h1>Fruits list</h1>

    <?php echo $this->partial(APP_VIEWS_DIR . '/samples/partials/list.phtml',
                              ['items' => $fruits]); ?>

    <h1>Fruits table</h1>
    <?php echo $this->partial(APP_VIEWS_DIR . '/samples/partials/table.phtml',
                              ['headers' => $tableHeaders,
                               'data' => $tableData]); ?>

</div>
