<?php /** @var $name string */ ?>
<div class="container">
    <h1><?php echo $this->translate('Vars sample');?></h1>

    <p>
        <?php echo $this->translate('This application route is registered as <strong>/samples/vars/:(string)name</strong>.');?>
    </p>
    <p>
        <?php echo $this->translate('The value of the route\'s section defined as <strong>:(string)name</strong> is converted into a var.');?>
    </p>

    <p>
        <?php echo $this->translate('Hello <mark>%s</mark>!', $name);?>
    </p>
</div>
