<?php
/** @var $headers array */
/** @var $data array */
?>
<?php if (isset($data) && count($data) > 0): ?>
    <table class="table table-striped">
        <!-- SAMPLE: Use a partial inside another partial -->
        <?php echo $this->partial(APP_VIEWS_DIR . '/samples/partials/table-headers.phtml',
                                  ['headers' => $headers]);?>
        <tbody>

        <?php foreach ($data as $row): ?>
            <tr>
            <?php foreach ($row as $item): ?>
                <td>
                    <?php echo $this->translate($item); ?>
                </td>
            <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>

        </tbody>

    </table>
<?php else: ?>
    <p><?php echo $this->translate('No data!'); ?></p>
<?php endif; ?>